Repository VROOM-Project/vroom, pull requests merged in 2021-02, with the labels that each got.

#449 VS 2019 compatibility
  .gitignore
  CHANGELOG.md
  include/getopt_win.h
  src/main.cpp
  src/problems/tsp/heuristics/local_search.cpp
  src/structures/generic/undirected_graph.cpp
  src/structures/typedefs.h
Labels: compilation, enhancement

#451 Test travis-ci.com setup
  .travis.yml
Labels: CI builds

#453 Update clang format
  CHANGELOG.md
  scripts/format.sh
  src/main.cpp
  src/problems/tsp/heuristics/local_search.cpp
  src/structures/typedefs.h
Labels: internals, refactor
