Repository VROOM-Project/vroom, pull requests merged in 2022-11, with the labels that each got.

#817 Extend CI strategy to include g++ and clang++ installed on Ubuntu 22.04
  .github/workflows/vroom.yml
  .github/workflows/vroom_libosrm.yml
  CHANGELOG.md
Labels: enhancement, CI builds

#819 Refactor `CVRP::solve` and `VRPTW::solve`
  CHANGELOG.md
  src/problems/cvrp/cvrp.cpp
  src/problems/vrp.h
  src/problems/vrptw/vrptw.cpp
Labels: refactor

#822 Fix off-by-one error in vrptw::MixedExchange validity check
  CHANGELOG.md
  src/problems/vrptw/operators/mixed_exchange.cpp
Labels: bug, VRPTW

#832 Fix regret underflow
  CHANGELOG.md
  src/algorithms/heuristics/heuristics.cpp
  src/algorithms/local_search/local_search.cpp
Labels: bug

#836 Fix crash with missing locations and only custom `costs` provided
  CHANGELOG.md
  src/structures/vroom/input/input.cpp
  src/structures/vroom/input/input.h
Labels: bug

#788 Better costs modelling at vehicle level
  CHANGELOG.md
  docs/API.md
  src/algorithms/heuristics/heuristics.cpp
  src/algorithms/heuristics/heuristics.h
  src/algorithms/local_search/local_search.cpp
  src/algorithms/local_search/local_search.h
  src/algorithms/local_search/operator.cpp
  src/algorithms/local_search/operator.h
  src/algorithms/local_search/route_split_utils.h
  src/algorithms/local_search/swap_star_utils.h
  src/algorithms/validation/choose_ETA.cpp
  src/problems/cvrp/cvrp.cpp
  src/problems/cvrp/operators/or_opt.cpp
  src/problems/cvrp/operators/pd_shift.cpp
  src/problems/cvrp/operators/relocate.cpp
  src/problems/cvrp/operators/reverse_two_opt.cpp
  src/problems/cvrp/operators/route_exchange.cpp
  src/problems/cvrp/operators/route_split.cpp
  src/problems/cvrp/operators/route_split.h
  src/problems/tsp/tsp.cpp
  src/problems/vrp.h
  src/problems/vrptw/operators/route_split.cpp
  src/problems/vrptw/operators/route_split.h
  src/problems/vrptw/vrptw.cpp
  src/structures/typedefs.h
  src/structures/vroom/cost_wrapper.cpp
  src/structures/vroom/cost_wrapper.h
  src/structures/vroom/input/input.cpp
  src/structures/vroom/input/input.h
  src/structures/vroom/input/vehicle_step.cpp
  src/structures/vroom/raw_route.cpp
  src/structures/vroom/raw_route.h
  src/structures/vroom/solution/route.cpp
  src/structures/vroom/solution/route.h
  src/structures/vroom/solution/step.cpp
  src/structures/vroom/solution_state.h
  src/structures/vroom/time_window.cpp
  src/structures/vroom/vehicle.cpp
  src/structures/vroom/vehicle.h
  src/utils/helpers.h
  src/utils/input_parser.cpp
Labels: feature request, API

#838 Add max travel time violations in plan mode
  docs/API.md
  src/algorithms/validation/choose_ETA.cpp
  src/structures/typedefs.h
  src/utils/output_json.cpp
Labels: enhancement, plan mode
