Repository VROOM-Project/vroom, pull requests merged in 2022-01, with the labels that each got.

#638 Remove duplicate definition of LocalSearch
  CHANGELOG.md
  src/problems/cvrp/cvrp.cpp
  src/problems/vrptw/vrptw.cpp
Labels: enhancement, compilation

#642 Python binding access to Amount and Matrix
  CHANGELOG.md
  src/structures/generic/matrix.h
  src/structures/vroom/amount.h
Labels: internals, downstream

#641 Refactor/exception
  CHANGELOG.md
  src/algorithms/heuristics/heuristics.cpp
  src/algorithms/validation/choose_ETA.cpp
  src/main.cpp
  src/routing/http_wrapper.cpp
  src/routing/libosrm_wrapper.cpp
  src/routing/ors_wrapper.cpp
  src/routing/osrm_routed_wrapper.cpp
  src/routing/valhalla_wrapper.cpp
  src/routing/wrapper.h
  src/structures/typedefs.h
  src/structures/vroom/cost_wrapper.cpp
  src/structures/vroom/input/input.cpp
  src/structures/vroom/time_window.cpp
  src/structures/vroom/tw_route.cpp
  src/structures/vroom/vehicle.cpp
  src/utils/exception.cpp
  src/utils/exception.h
  src/utils/helpers.h
  src/utils/input_parser.cpp
Labels: enhancement, internals

#659 Add local search operators stats
  CHANGELOG.md
  src/algorithms/local_search/local_search.cpp
  src/algorithms/local_search/local_search.h
  src/algorithms/local_search/operator.cpp
  src/algorithms/local_search/operator.h
  src/problems/cvrp/cvrp.cpp
  src/problems/cvrp/operators/cross_exchange.cpp
  src/problems/cvrp/operators/intra_cross_exchange.cpp
  src/problems/cvrp/operators/intra_exchange.cpp
  src/problems/cvrp/operators/intra_mixed_exchange.cpp
  src/problems/cvrp/operators/intra_or_opt.cpp
  src/problems/cvrp/operators/intra_relocate.cpp
  src/problems/cvrp/operators/mixed_exchange.cpp
  src/problems/cvrp/operators/or_opt.cpp
  src/problems/cvrp/operators/pd_shift.cpp
  src/problems/cvrp/operators/relocate.cpp
  src/problems/cvrp/operators/reverse_two_opt.cpp
  src/problems/cvrp/operators/route_exchange.cpp
  src/problems/cvrp/operators/swap_star.cpp
  src/problems/cvrp/operators/two_opt.cpp
  src/problems/cvrp/operators/unassigned_exchange.cpp
  src/problems/vrptw/vrptw.cpp
Labels: internals, Local search

#559 Improve Performance on PD Instances
  CHANGELOG.md
  src/algorithms/local_search/insertion_search.h
  src/algorithms/local_search/local_search.cpp
  src/problems/cvrp/operators/pd_shift.cpp
  src/problems/vrptw/operators/pd_shift.cpp
  src/problems/vrptw/operators/pd_shift.h
  src/structures/vroom/amount.h
  src/structures/vroom/raw_route.cpp
  src/structures/vroom/raw_route.h
Labels: enhancement, internals, refactor, PDPTW
