Repository VROOM-Project/vroom, pull requests merged in 2022-09, with the labels that each got.

#752 Use Eval struct over plain Cost/Gain types
  CHANGELOG.md
  src/algorithms/heuristics/heuristics.cpp
  src/algorithms/local_search/insertion_search.h
  src/algorithms/local_search/local_search.cpp
  src/algorithms/local_search/local_search.h
  src/algorithms/local_search/operator.cpp
  src/algorithms/local_search/operator.h
  src/algorithms/local_search/swap_star_utils.h
  src/problems/cvrp/operators/cross_exchange.cpp
  src/problems/cvrp/operators/cross_exchange.h
  src/problems/cvrp/operators/intra_cross_exchange.cpp
  src/problems/cvrp/operators/intra_cross_exchange.h
  src/problems/cvrp/operators/intra_exchange.cpp
  src/problems/cvrp/operators/intra_mixed_exchange.cpp
  src/problems/cvrp/operators/intra_mixed_exchange.h
  src/problems/cvrp/operators/intra_or_opt.cpp
  src/problems/cvrp/operators/intra_or_opt.h
  src/problems/cvrp/operators/intra_relocate.cpp
  src/problems/cvrp/operators/intra_two_opt.cpp
  src/problems/cvrp/operators/mixed_exchange.cpp
  src/problems/cvrp/operators/mixed_exchange.h
  src/problems/cvrp/operators/or_opt.cpp
  src/problems/cvrp/operators/or_opt.h
  src/problems/cvrp/operators/pd_shift.cpp
  src/problems/cvrp/operators/pd_shift.h
  src/problems/cvrp/operators/relocate.cpp
  src/problems/cvrp/operators/reverse_two_opt.cpp
  src/problems/cvrp/operators/route_exchange.cpp
  src/problems/cvrp/operators/swap_star.cpp
  src/problems/cvrp/operators/swap_star.h
  src/problems/cvrp/operators/two_opt.cpp
  src/problems/cvrp/operators/unassigned_exchange.cpp
  src/problems/vrptw/operators/pd_shift.cpp
  src/problems/vrptw/operators/pd_shift.h
  src/problems/vrptw/operators/swap_star.cpp
  src/problems/vrptw/operators/swap_star.h
  src/structures/typedefs.h
  src/structures/vroom/eval.h
  src/structures/vroom/solution_state.cpp
  src/structures/vroom/solution_state.h
  src/structures/vroom/vehicle.h
  src/utils/helpers.h
Labels: internals, refactor

#777 Pass zero amount directly instead of its size
  CHANGELOG.md
  src/algorithms/validation/check.cpp
  src/structures/vroom/solution/solution.cpp
  src/structures/vroom/solution/solution.h
  src/structures/vroom/solution/summary.cpp
  src/structures/vroom/solution/summary.h
  src/utils/helpers.h
Labels: enhancement, internals

#780 Handle vehicle max travel time
  CHANGELOG.md
  docs/API.md
  src/algorithms/heuristics/heuristics.cpp
  src/algorithms/local_search/insertion_search.h
  src/algorithms/local_search/local_search.cpp
  src/algorithms/local_search/operator.cpp
  src/algorithms/local_search/operator.h
  src/algorithms/local_search/swap_star_utils.h
  src/problems/cvrp/operators/cross_exchange.cpp
  src/problems/cvrp/operators/intra_cross_exchange.cpp
  src/problems/cvrp/operators/intra_exchange.cpp
  src/problems/cvrp/operators/intra_mixed_exchange.cpp
  src/problems/cvrp/operators/intra_mixed_exchange.h
  src/problems/cvrp/operators/intra_or_opt.cpp
  src/problems/cvrp/operators/intra_or_opt.h
  src/problems/cvrp/operators/intra_relocate.cpp
  src/problems/cvrp/operators/intra_two_opt.cpp
  src/problems/cvrp/operators/mixed_exchange.cpp
  src/problems/cvrp/operators/mixed_exchange.h
  src/problems/cvrp/operators/or_opt.cpp
  src/problems/cvrp/operators/or_opt.h
  src/problems/cvrp/operators/pd_shift.cpp
  src/problems/cvrp/operators/pd_shift.h
  src/problems/cvrp/operators/relocate.cpp
  src/problems/cvrp/operators/reverse_two_opt.cpp
  src/problems/cvrp/operators/route_exchange.cpp
  src/problems/cvrp/operators/two_opt.cpp
  src/problems/cvrp/operators/unassigned_exchange.cpp
  src/problems/vrptw/operators/pd_shift.cpp
  src/structures/vroom/solution_indicators.h
  src/structures/vroom/solution_state.cpp
  src/structures/vroom/solution_state.h
  src/structures/vroom/vehicle.cpp
  src/structures/vroom/vehicle.h
  src/utils/helpers.h
  src/utils/input_parser.cpp
Labels: feature request
