Repository VROOM-Project/vroom, pull requests merged in 2023-10, with the labels that each got.

#1009 Account for cost per km
  CHANGELOG.md
  docs/API.md
  src/algorithms/validation/choose_ETA.cpp
  src/structures/typedefs.h
  src/structures/vroom/cost_wrapper.cpp
  src/structures/vroom/cost_wrapper.h
  src/structures/vroom/vehicle.cpp
  src/structures/vroom/vehicle.h
  src/utils/helpers.cpp
  src/utils/input_parser.cpp
Labels: feature request

#1014 Remove unused `tw_length` member from `Job` and associated code
  CHANGELOG.md
  src/structures/vroom/job.cpp
  src/structures/vroom/job.h
  src/structures/vroom/time_window.cpp
Labels: refactor

#1008 Work on reducing operators scope
  CHANGELOG.md
  src/algorithms/local_search/local_search.cpp
  src/algorithms/local_search/swap_star_utils.h
  src/algorithms/local_search/top_insertions.cpp
  src/algorithms/local_search/top_insertions.h
  src/structures/vroom/bbox.cpp
  src/structures/vroom/bbox.h
  src/structures/vroom/cost_wrapper.h
  src/structures/vroom/input/input.h
  src/structures/vroom/location.cpp
  src/structures/vroom/location.h
  src/structures/vroom/solution_indicators.h
  src/structures/vroom/solution_state.cpp
  src/structures/vroom/solution_state.h
  src/structures/vroom/vehicle.cpp
Labels: Local search, core

#1023 Replace clang++-14 with clang++-15 in CI
  .github/workflows/vroom.yml
  .github/workflows/vroom_libosrm.yml
  CHANGELOG.md
  scripts/format.sh
  src/problems/tsp/heuristics/christofides.cpp
  src/problems/tsp/heuristics/local_search.cpp
  src/routing/libosrm_wrapper.cpp
Labels: compilation, CI
